project_name                           : "tsabc2"
id_range_for_simulations               : [0, 3] # unique id per simulation
nbatch_simulations                     : 3
nthreads_per_batch                     : 3 # needs to be smaller or equal to nbatch
####
# nthreads: how many parallele processes to run nbatch simulations
# e.g. nbatch = 100 and nthreads = 20:
#   20 processes in parallel and 5 simulations one after eachother on every process
#   it makes sense to have nbatch as a multiple of nthreads
randint_range_for_drawing_prior        : [0, 4294967296] # half-open
randint_range_for_simulations          : [0, 4294967296] # half-open
# prior parameter range ("lower", "upper", "numtype", "distributiontype")
population_size_recent                 : [5e4, 1e6, "int", "uniform"]
population_size_ancient                : [5e4, 1e6, "int", "uniform"]
population_size_change_time            : [1e4, 1e6, "int", "uniform"]
selfing_rate_recent                    : [0.5, 1, "float", "uniform"]
selfing_rate_ancient                   : [0, 0.2, "float", "uniform"]
selfing_rate_change_time               : [1e4, 1e6, "int", "uniform"]
# specifications concerning the coalescent simulations
recombination_rate                     : 3.5383425438512384e-08
mutation_rate                          : 4e-09
chromosome_length                      : 5e6
sample_size_simulation                 : 12
generations_dtwf                       : 1000
# specifications concerning the summarizing statistics
sfs_stat_properties                    : ["site", "folded"] # site statistic
ld_num_of_considered_mutations         : 2000
ld_binning_breaks                      : [1, 6105.472, 11379.62, 21209.786,
                                          39531.638, 73680.63, 137328.871,
                                          255958.978, 477066.461, 889175.328,
                                          1657280.126, 3088904.21, 5757221.770,
                                          10730537.517, 2e7]
tl_true_max_number_of_pairs            : 25 # same number is used for both tm
tl_true_number_of_bins                 : 20
tl_true_binning_scale_factor           : 2 # how the distr of breakpoints is
tl_true_minimal_length_bin_size        : 2000 # the shortest length bin
tm_win_properties                      : [2e4, 2e4, "site", 20] # window-size, window-step, stat-mode, number of discretized bins
tm_win_binning_scale_factor            : 2 # how the distr of breakpoints is
# specifications for pods with fixed parameters
pod_number_of_simulations_per          : 100
nbatch_pod                             : 25
pod_population_size_recent             : [200_000]
pod_population_size_ancient            : [425_000]
pod_population_size_change_time        : [500_000]
pod_selfing_rate_recent                : [0.99]
pod_selfing_rate_ancient               : [0.1]
pod_selfing_rate_change_time           : [475_000]
# specifications for the performance analysis
number_of_tolerated_simulations        : 1000
point_estimate                         : ["mode"] # mean, median or mode
regression_method                      : ["loclinear"] # , "neuralnet"] # abc package
number_max_pls_for_transformation      : 31
pls_components_for_loclinear           : [20]

sumstat_combination_to_use:
  - ["sfs", "ld"]
  - ["tm_win"]
  - ["sfs", "ld", "tm_win"]
# alternative model specifications
id_range_for_alt_model_simulations     : [0, 1_000] # unique id per simulation
nbatch_alt_model_simulations           : 20
# prior parameter range ("lower", "upper", "numtype", "distributiontype")
alt_model_population_size_recent       : [5e4, 1e6, "int", "uniform"]
alt_model_population_size_ancient      : [5e4, 1e6, "int", "uniform"]
alt_model_population_size_change_time  : [1e4, 1e6, "int", "uniform"]
alt_model_selfing_rate                 : [0.5, 1, "float", "uniform"]
# model_choice_parameters
model_choice_tolerance                 : 1000

